name: data_class_plugin
version: 1.1.0
description: A tool that uses Dart's Analyzer to generate code on-the-fly.

homepage: https://github.com/spideythewebhead/dart_data_class_plugin
repository: https://github.com/spideythewebhead/dart_data_class_plugin
documentation: https://github.com/spideythewebhead/dart_data_class_plugin
issue_tracker: https://github.com/spideythewebhead/dart_data_class_plugin/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  args: ^2.4.2
  dart_style: ^2.3.3
  meta: ^1.10.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.8.3
  file: ">=6.0.0 <8.0.0"
  tachyon: ^0.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
