name: data_class_plugin
version: 0.2.0
description: A tool that uses Dart's Analyzer to generate code on-the-fly.

homepage: https://github.com/spideythewebhead/dart_data_class_plugin
repository: https://github.com/spideythewebhead/dart_data_class_plugin
documentation: https://github.com/spideythewebhead/dart_data_class_plugin
issue_tracker: https://github.com/spideythewebhead/dart_data_class_plugin/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.0.0 <6.0.0"
  analyzer_plugin: ">=0.10.0 <1.0.0"
  args: ^2.3.1
  dart_style: ^2.2.4
  meta: ^1.8.0
  yaml: ^3.1.1
  glob: ^2.1.1
  path: ^1.8.2
  file: ^6.1.4
  stack_trace: ^1.10.0
  watcher: ^1.0.2
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
